name: Playwright Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: GMAIL_SMTP

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build Docker image
              run: docker build -t my-playwright-tests .

            - name: Run Playwright tests
              run: docker run --rm my-playwright-tests

            - name: Upload Playwright report
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: playwright-report
                  path: playwright-report
            # Debugging step
            - name: List files
              run: ls -R

            - name: Send Email with Report Link
              if: always()
              uses: dawidd6/action-send-mail@v3
              with:
                  server_address: ${{ secrets.SMTP_SERVER }}
                  server_port: ${{ secrets.SMTP_PORT }}
                  username: ${{ secrets.SMTP_USERNAME }}
                  password: ${{ secrets.SMTP_PASSWORD }}
                  subject: Playwright Test Report
                  body: |
                      The Playwright tests have completed.

                      You can view the HTML report at the following link:

                      [View Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)

                      Or see the attached report.
                  to: netanelharush2@gmail.com
                  from: GitHub Actions <netanelharush2@gmail.com>
                  attachments: 'playwright-report/index.html'
